### ISSUE TITLE
Getting two errors

### ISSUE THREAD

**Issue by raj-aayush-65** [NV404/noob#1]
Cannot read count of undefined and the server responded with a status of 403(forbidden)

![image](https://user-images.githubusercontent.com/63776877/123947636-38822900-d9be-11eb-82f9-fe80705dedf4.png)

![image](https://user-images.githubusercontent.com/63776877/123947699-49329f00-d9be-11eb-8a3b-a8f779ee4164.png)

I Guess the error is due to some firebase permission error, but I checked all stuffs and permission, and also checked for localhost to allow fetching data. Well it's only happening for the images.

**Comment by NV404** [comment]
@rajaayush65 can you check your firestore if there is "total" named document available in "Like" subcollection of post which you are reading and let me know.

**Comment by raj-aayush-65** [comment]
yes their is 
![image](https://user-images.githubusercontent.com/63776877/124061002-c35d3500-da4b-11eb-85cc-1f4ce2a77da3.png)

I guess their is some error with firebase permissions because in the console , I am getting a response like ""url" parameter is valid but upstream response is invalid" such in the browser console.

Also in the Terminal I am getting such a response

" FetchError: request to https://firebasestorage.googleapis.com/v0/b/twitter-clone-6d3a7.appspot.com/o/ProfilePic%2Fdefault.png?alt=media failed, reason: read ECONNRESET
    at ClientRequest.<anonymous>  "

But this image gets loaded , in a while
![image](https://user-images.githubusercontent.com/63776877/124061520-99f0d900-da4c-11eb-9810-cce9888e2178.png)


their is no error in fetching this, pretty sure the error lies with some firebase permission

![image](https://user-images.githubusercontent.com/63776877/124061593-c4db2d00-da4c-11eb-98e4-a44ea5b25713.png)

cause the response of the above error is " "url" parameter is valid but upstream response is invalid "

**Comment by NV404** [comment]
You have to make your Firebase storage public.
